I've fixed makefile and brainwas.cpp
HaikuArchives/BrainWash pull request #2
Opened 2017-01-13 17:26 UTC by dacianf

2017-01-13 17:30 UTC, mmuman commented on BrainWash.cpp
> +		: BMenuField(frame, NULL, label, (BMenu*)(new BPopUpMenu("resolution")))
The BMenu * cast seems useless, BPopUpMenu is a BMenu subclass.

2017-01-13 17:33 UTC, mmuman commented
For the commit log, one usually use the imperative "Fix ..." or the past "Fixed ...", but not the at the first person.

2017-01-13 18:39 UTC, scottmc commented
While you are at it, please also use "rc -d BrainWash.rsrc" to create a BrainWash.rdef and then add the .rdef to the makefile, in place of the .rsrc file.  See https://www.haiku-os.org/documents/dev/compile_them_resources

2017-01-13 18:40 UTC, humdingerb requested changes

2017-01-13 18:40 UTC, humdingerb commented on BrainWash.cpp
> +#include <PopUpMenu.h>
You can remove all the app/, interface/, game/ above and sort PopUpMenu.h into it alphabetically. In fact sort all includes alphabetically while you're at it.

2017-01-13 18:40 UTC, humdingerb commented on makefile
> +include $(DEVEL_DIRECTORY)/etc/makefile-engine
line 17: screen savers are actuall of type "SHARED".
line 83: remove the TRUE

2017-01-13 18:42 UTC, scottmc commented
Also remove the _APP_ symlink from the repo, as this won't be needed, as the install step will be handled by the recipe.

2017-01-13 20:52 UTC, dacianf commented on makefile
> +include $(DEVEL_DIRECTORY)/etc/makefile-engine
@humdingerb what is about those line from 97-100?

2017-01-14 00:33 UTC, merged

2017-01-14 07:17 UTC, humdingerb commented on makefile
> +include $(DEVEL_DIRECTORY)/etc/makefile-engine
Github lets me only comment on lines that were changed in the PR. Being lazy, I just clicked on a changed line and specified the lines I had comments on in the comment...